---
format: pdf
editor: visual
---

### Caso k = 1

```{r,echo=FALSE,eval=TRUE,fig.align='center',fig.width=7,fig.height=4}

g <- function(theta){
  1/theta
}

theta <- 1
x <- 1:1000

plot(
  x, rep(g(theta), length(x)),
  type = "l",
  lwd = 2,
  xlab = "t",
  ylab = expression(alpha(t)),
  main = bquote(theta == .(theta))
)

f <- function(theta){
  1/theta
}

x <- seq(0.01, 5, by = 0.01)

plot(
  x, f(x),
  type = "l",
  lwd = 2,
  xlab = expression(theta),
  ylab = expression(alpha(t)),
  main = expression(alpha(t) == frac(1, theta))
)
```

### Caso k \> 1 

```{r,echo=FALSE,eval=TRUE,fig.align='center',fig.width=7,fig.height=4}

g <- function(t, k){
  k * t^(k - 1)
}

t <- seq(0, 1, length.out = 1000)
ks <- c(1.5,2, 3, 4, 5, 10)

cores <- rainbow(length(ks))

plot(
  t, g(t, ks[1]),
  type = "l",
  lwd = 3,
  col = cores[1],
  ylim = c(0, max(sapply(ks, function(k) max(g(t, k))))),
  xlab = "t",
  ylab = expression(alpha(t)),
  main = expression(alpha(t) == k*t^(k-1) ~~ "(k > 1)")
)

for(i in 2:length(ks)){
  lines(
    t,
    g(t, ks[i]),
    col = cores[i],
    lwd = 2
  )
}
grid()
legend(
  "topleft",
  legend = paste("k =", ks),
  col = cores,
  lwd = c(3, rep(2, length(ks)-1))
)
```

### Caso k \< 1 

```{r,echo=FALSE,eval=TRUE,fig.align='center',fig.width=7,fig.height=4}

g <- function(t, k){
  k * t^(k - 1)
}

t <- seq(0.001, 1, length.out = 1000)
ks <- c(0.9, 0.8, 0.7, 0.5, 0.3, 0.1)

cores <- hcl.colors(length(ks), "Dark 3")

plot(
  t, g(t, ks[1]),
  type = "l",
  lwd = 3,
  col = cores[1],
  log = "y",
  xlab = "t",
  ylab = expression(alpha(t)),
  main = expression(alpha(t) == k*t^(k-1) ~~ "(k < 1)")
)

for(i in 2:length(ks)){
  lines(
    t,
    g(t, ks[i]),
    col = cores[i],
    lwd = 3
  )
}

grid()

legend(
  "topright",
  legend = paste("k =", ks),
  col = cores,
  lwd = 3,
  bty = "n"
)
```
